# Generated by Django 4.2.7 on 2023-11-19 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_invitation_delete_lockscreen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Storekeeper'), (4, 'Staff')]),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='pos.branch'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Storekeeper'), (4, 'Staff')]),
        ),
    ]
