# Generated by Django 4.2.7 on 2023-11-19 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_profile_customuser_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Storekeeper'), (4, 'Staff')], null=True),
        ),
    ]
