# Generated by Django 4.2.7 on 2023-11-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0008_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
