# Generated by Django 4.2.7 on 2023-11-24 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_unit_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='auth_user_id',
        ),
    ]
