# Generated by Django 4.2.7 on 2023-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0010_remove_notification_auth_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
