# Generated by Django 4.2.7 on 2023-11-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0013_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
