# Generated by Django 4.2.7 on 2023-11-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0014_remove_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(blank=True, choices=[('Warehouse', 'Warehouse'), ('Branch', 'Branch')], max_length=10, null=True),
        ),
    ]
