# Generated by Django 4.2.7 on 2024-02-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0018_sale_discount_sale_remaining_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='brn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='vat',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Store Manager'), (3, 'Staff')], null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Store Manager'), (3, 'Staff')]),
        ),
    ]
