# Generated by Django 4.2.7 on 2024-03-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0019_supplier_address_supplier_brn_supplier_vat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_started',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='permit_granted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
