# Generated by Django 4.2.7 on 2024-03-18 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0020_profile_date_started_profile_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='StockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reference_no', models.CharField(max_length=6, unique=True)),
                ('note', models.TextField(blank=True)),
                ('quantity', models.IntegerField()),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
